### PR TITLE
SLING-8314 : JCR Installer writeback  -  convert primitive arrays to …

### PR DESCRIPTION
**Pull request by ashokpanghal**
…Object arrays

### CODE REVIEW

**Comment by ashokpanghal** [comment]
Fix given in this patch converts all primitive arrays into respective Object Arrays so that org.apache.felix.cm.file.ConfigurationHandler creates an outputstream with the uppercase prefixes as documented here https://sling.apache.org/documentation/bundles/configuration-installer-factory.html#configuration-files-config-

**Comment by rombert** [comment]
A SonarQube report for the changes added _only by this pull request_ was generated. Please review it at https://builds.apache.org/job/Sling/job/sling-org-apache-sling-installer-provider-jcr/job/PR-1/1/artifact/target/sonar/issues-report/issues-report-light.html

**Comment by rombert** [comment]
Not sure who would be best to review this ... Maybe one of @cziegeler , @karlpauls , @kwin ?

**Comment by kwin** [comment]
Please compare with the discussion at https://www.mail-archive.com/dev@sling.apache.org/msg83978.html. I have prepared a clarification on the documentation side (https://github.com/apache/sling-site/pull/34). After this has been merged I would tend to close this one as "Won't Fix".

**Comment by kwin** [comment]
@ashokpanghal Thanks for this PR, but we won't merge it. In general primitive arrays should work fine and the documentation has been updated as well. For further details refer to https://issues.apache.org/jira/browse/SLING-8314.

**Pull request closed without merging**
